### ISSUE TITLE
the blocked_expressions list somehow gets erased again and again

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#15]
Trying to reproduce it, it seems like saving anything in the general tab resets the readability tab (but not the other way around).

Another issue is that you can make a change in one tab, switch to another and then save - only the changes in the current tab will be saved, even though there was no warning. I think your code should probably consider all the tabs as one form .

**Comment by drorsnir** [comment]
Actually, saving *any* tab will cause the settings of other tabs to be erased (except for the general tab, which retains its settings).

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/301c28c76fb1726d6abfd8545bba33507eea8057

**Comment by drorsnir** [comment]
Great
