### ISSUE TITLE
blocked_expressions highlighting sometimes messed up

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#17]
See the following two screenshots, from this page:
https://www.kolzchut.org.il/he/הפסקת_הריון

It starts out OK, but then we suddently have whole examples in bold.  It looks like maybe you add the `<b>` tags and then cut the string, causing the tags to flow over.

![Screenshot 2021-12-13 at 17-48-41 הפסקת הריון](https://user-images.githubusercontent.com/3416107/145843804-6e68cdf3-fcb2-40ba-8633-699843cb6c6c.png)
![Screenshot 2021-12-13 at 17-48-24 הפסקת הריון](https://user-images.githubusercontent.com/3416107/145843813-f82bfdaf-d343-4b04-baba-54789e0ac27b.png)

**Comment by nischayn22** [comment]
I tried to see this live in action, but on this view it doesn't show me anything: https://www.kolzchut.org.il/he/Special:PageQuality/report?page_id=4497

Could you please share the link where I can find the HTML for the results?

**Comment by drorsnir** [comment]
So, I can recreate it using this revision:
www.kolzchut.org.il/w/he/index.php?title=הפסקת_היריון&action=edit&oldid=454915


Now, it's actually very simple (but took me over an hour to debug):
1. Let's use the word "הריון" as the blocked expression
2. The DB field is for examples 100 characters long
1. The offending sentence is "להפסיק את ההריון. סעיף 316 לחוק העונשין מפרט את המקרים שבהם יש לוועדה סמכות לאשר הפסקת הריון"
1. The sentence you take is 92 characters long, and then you add `<b></b>` - another 8 characters. This should work perfectly, only the expression shows _twice_ - 8 characters too many.
1. so you end up with this:
  - `להפסיק את ה<b>הריון</b>. סעיף 316 לחוק העונשין מפרט את המקרים שבהם יש לוועדה סמכות לאשר הפסקת <b>הריון</b>`
  - which gets cut down to `להפסיק את ה<b>הריון</b>. סעיף 316 לחוק העונשין מפרט את המקרים שבהם יש לוועדה סמכות לאשר הפסקת <b>הר`
  1.  And we have a runaway `<b>` tag...
  
  The simplest solution is to use substr_replace() instead of str_replace(), and replace only the 1st occurrence of the expression.
  
  (And while you're at it, could you remove the `trim( $blocked_expression )`? Many times we need to add a space before and/or after the expression, so that it won't be considered a match in the middle of another word.)

**Comment by nischayn22** [comment]
I don't fully understand this. But do you think just adding str_replace with count 1 should solve the problem?

Here's the function definition:

str_replace(
    array|string $search,
    array|string $replace,
    string|array $subject,
    int &$count = null
): string|array

**Comment by drorsnir** [comment]
[Count](https://www.php.net/manual/en/function.str-replace.php#:~:text=,count,-If%20passed%2C%20this) doesn't do what you think it does:
`If passed, this will be set to the number of replacements performed`

So it doesn't limit the number of replacements. Otherwise, this would be perfect.
Use whatever you need to make sure only a single replacement is performed.

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/00fed7378fcebf97572dc292612838c39513315c

**Comment by drorsnir** [comment]
Seems to work well :-)
