### ISSUE TITLE
Add filters in reports

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#18]
Relevant reports:
- [x]  main dashboard
- [x]  list report
- [x]  history 

Filters:
- [x] Content area
- [x] Article type
- [ ] pageviews
  - This is currently unimplemented on our side; You should add the fields to sort by range (X..Y), where either parameters is optional, and assume the the code to handle this would be pretty much identical to the code used for the others - something along the lines of `PageViews::getJoin( 'page_id', X, Y)`.

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/7369073488ed93839a1cbcc0f35cce0a9dca0bdf
I am closing this as PageViews is not implemented yet. Lets add it when we can test it.
