### ISSUE TITLE
Trigger audits rerun after a configuration change

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#21]
Since this will be a massive resource usage, you should:
1. Require user to confirm again before save
2. Run in the background as jobs or similar - I believe Cargo has a mechanism that does this when recreating tables

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/8fa55867d884ff04be29f36e23100433ee9bde2b

**Comment by drorsnir** [comment]
Good job! (lame pun intended)
