### ISSUE TITLE
Use a MW pager for lists

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#22]
Lists, log, etc. Do not forget query-level sorting by field (currently done by JS).

**Comment by nischayn22** [comment]
How would this work for the improvements and declines lists? A simple join query wouldn't give the result in this case. Or do you want me to do this only for the rest of the lists?

**Comment by drorsnir** [comment]
Do you mean the dashboard, or the drill-down from it to the lists? I'm not sure why the lists wouldn't work with a pager, but you can leave that part to the end.

**Comment by nischayn22** [comment]
This wouldn't work directly for any reports. For eg. the list of pages that are being scored as red isn't a single query right now. We calculate the score on the fly.

Do you think we should start maintaining a separate table for the score?

**Comment by drorsnir** [comment]
I'm sorry, but I don't see more than a single query anywhere - but you're correct that it's a problem to implement a pager with sorting when the score is calculated on the fly - you would have to query everything just to know the total score and then show the top X rows.

The issue I'm trying to sovle here is the performance on page - right now even with only a few thousand rows, the browser doesn't really like that huge table, so I much prefer to have a normal pager. Therefore, if you think we should have a separate score table for that (we actually did have `page_issues_summary` in the original spec), then go with that. Thanks!

**Comment by nischayn22** [comment]
Added in https://github.com/nischayn22/PageQuality/commit/7d2710fdf617406f25f03fe14ddd332b0dfc8532
Its WIP and needs some fixes but I would recommend you try it out.
