### ISSUE TITLE
Save the specific blocked expression in the DB

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#23]
This would allow us one day to actually see a breakdown of usage.

You should also refrain from saving the highlight of the word in the "example" field; this is better done on the fly.

**Comment by nischayn22** [comment]
Any reason why the breakdown cannot be generated on the fly?

Did you mean the example field shouldn't have the <b> tags and it should be added on the fly? This would mean customizing the code used to display the page quality report for one type of scorer, my design was done in a way that each scorer has the logic for its own use case.

**Comment by drorsnir** [comment]
Ah, I see regarding the encapsulation - one way to solve that will be to also allow each scorer to override its display in the report, but there's no real need to go there. So no, don't stop saving the current example.

How can you generate a breakdown for all pages on the fly without saving the expression itself?

**Comment by nischayn22** [comment]
I meant, we could do a quick run of one scorer for all the pages to generate the breakdown on the fly. Another approach would be to put a specific CSS class in the example and generate it from the examples.

**Comment by drorsnir** [comment]
I see. I'm not sure how fast this will work, considering it takes quite a while to run everything for every page - but let's postpone this for now.
