### ISSUE TITLE
Fix display for declining/improving pages

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#29]
When clicking the number of declining or improving pages, we are taken to a generic report for them, not to a list of pages according to the previous filter (date, etc.).

Followup to #19. See also #28.

![image](https://user-images.githubusercontent.com/3416107/156002771-e04c6b49-9b80-4ec0-a944-b86acac54bd4.png)

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/6f56379e12adc170e90862242bb56b12636f5512

**Comment by FreedomFighterSparrow** [comment]
Excellent.
