### ISSUE TITLE
Bug: when reporting on the number of pages with an issue, it actually shows the number of issues

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#33]
If you look at this, we get numbers such as 9,488 and 14,566 - more than the number of pages in the wiki:
![image](https://user-images.githubusercontent.com/3416107/162612214-8a07eb60-51a5-4623-b643-6494477b2f44.png)

I guess you're summing the total number of issues, not the distinct pages with the issue.

**Comment by nischayn22** [comment]
Fixed in https://github.com/nischayn22/PageQuality/commit/46ccaf8447f30b84cac3566b56bd2d1b91f7b972

**Comment by drorsnir** [comment]
Great :-)
