### ISSUE TITLE
On first save, no quality score shows

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#34]
It shows only on second save

**Comment by FreedomFighterSparrow** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/3416107/168675920-bdb8b808-996b-41ed-a9c4-962c46fb793a.png">

**Comment by nischayn22** [comment]
Works fine for me. Which MW version are you using? I am on 1.35.2

**Comment by drorsnir** [comment]
Well, I see what happens here - isPageScoreable() checks for the article type, but apparently it wasn't saved yet by MediaWiki. I'm not even sure there's a solution for it, so let's a label for "stalled" issues and carry on.

**Comment by nischayn22** [comment]
Ah, I see. Great investigation :)

**Comment by drorsnir** [comment]
No relevant for Nischay - our problem
