### ISSUE TITLE
The feedback score dialog looks odd in RTL

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#5]
See screenshot - these are the issues I see:

1. It should probably float to the left (keep in mind that all of bootstrap's classes are mirrored for RTL)
2. `.jconfirm-bg` probably shouldn't take all that space to both sides (see those almost invisible lines?)
3. It should probably be wider - try to accomade the length of each "evidence" line, so each takes only a single line
4. Although I suspect we asked you to remove it previously, Amitay thinks each issue line should have a bullet. Maybe just remove `.list-group` from the `<ul>`?

![image](https://user-images.githubusercontent.com/3416107/128644616-768978d6-6601-4a4e-97c0-e0295d3d27a2.png)

**Comment by nischayn22** [comment]
I don't think I understand all of these. I think it would be best if we discuss and fix them live on a call.
